### ISSUE TITLE
Not seeing kuna_event in services

### ISSUE THREAD

**Issue by jmutnick** [marthoc/kuna#14]
I do not see kuna_event in the kuna services.  Am I missing something?

**Comment by JuliusLedoux** [comment]
The only services that I see are: kuna.enable_notifications and kuna.disable_notifications. But it is working for me as expected.

**Comment by marthoc** [comment]
There are only two services as @JuliusLedoux correctly points out. `kuna_event` is the event type of the event the component fires on the event bus when a new recording is found on the poll of the Kuna API, it has nothing to do with services.

**Comment by jmutnick** [comment]
Thanks for the quick feedback.  My Kuna device does not always pick up movement, but after I posted this it started working again and I found the files in the download directory.  Appreciate the responses!
