### ISSUE TITLE
Can't even get started

### ISSUE THREAD

**Issue by jsmwrench** [marthoc/kuna#49]
Hi.

I appreciate all of your work to get this to us all.  That said, I'm new to Home Assistant and I'm having trouble even getting started.  Your first instruction states: "Add "marthoc/kuna" as a custom repository in HACS under "Settings"."  _**HOW**_ do I add/make a "custom repository"?  I can't find this option anywhere in Settings.

Thank you for your time,
Ron.

**Comment by mcfarlde** [comment]
You need to install HACS and then in integrations there are three dots top right that let you specify where the custom repository comes from.

**Comment by jsmwrench** [comment]
Thank you.  Being new, I didn't realize Home Assistant and HACS were two different inteties. There are no step-by-step instructions, but you cleared it up enough for me to figure out the rest.  I appreciate you time.

**Comment by jsmwrench** [comment]
This issue can be closed.  Thanks again.
